name: Scrape Instagram

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape followers
        id: scrape
        run: |
          python main.py --no-visualize --no-analyze --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}

      - name: Commit and push data
        id: commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/connections.json
          git commit -m "Add scraped data"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
