name: Run main.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
with:
  python-version: '3.x'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Generate figures
  id: generate_figures
  run: |
    if [ ! -f output/cluster.html ] || [ ! -f output/cluster.png ] || [ ! -f output/network.html ] || [ ! -f output/network.png ]; then
      python main.py --no_scrape True
      echo "::set-output name=figures_generated::true"
    else
      echo "::set-output name=figures_generated::false"

- name: Commit and push figures
  if: steps.generate_figures.outputs.figures_generated == 'true'
  run: |
    git config --global user.name 'github-actions'
    git config --global user.email 'actions@github.com'
    git add output/network.png
    git add output/network.html
    git add output/cluster.png
    git add output/cluster.html
    git commit -m "Add workflow generated figures"
    git push origin main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}