name: Scrape Instagram

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape
        id: scrape
        run: |
          if [ ! -f output/cluster.html ] || [ ! -f output/cluster.png ] || [ ! -f output/network.html ] || [ ! -f output/network.png ]; then
            python main.py --no_scrape True
            echo "::set-output name=figures_generated::true"
          else
            echo "::set-output name=figures_generated::false"
          fi

      - name: Commit and push figures
        if: steps.generate_figures.outputs.figures_generated == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/connections.json
          git commit -m "Add workflow generated figures"
          git push origin mai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
